name: Run CF
on: 
  push:
    branches: [cf]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Reapsaw repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # - name: Install python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.6

      # - name: Install aws cli
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install
      #     aws --version


      #     echo "[default]" >> ~/.aws/credentials
      #     echo "aws_access_key_id=$AWS_ID" >> ~/.aws/credentials
      #     echo "aws_secret_access_key=$AWS_KEY" >> ~/.aws/credentials
      #     cat  ~/.aws/credentials
      #     aws s3 ls

        # env:
        #   AWS_ID: ${{ secrets.AWS_ID }}
        #   AWS_KEY: ${{ secrets.AWS_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY }}
          aws-region: us-east-1

      - name: AWS CLI
        run: |
          aws s3 ls
          ls -la
          sudo apt install zip -y
          zip -r filename.zip devo-engine
          ls -la
          aws s3 cp filename.zip s3://alex-test-988442/lambdas/lambda_function.zip
      

      